export enum BlockType {
 TEXT = "text",
 IMAGE = "image",
 CALENDER = "calender",
 H1 = "h1",
 H2 = "h2",
 H3 = "h3",
 H4 = "h4",
 H5 = "h5",
 H6 = "h6",
 TODOLIST = "todolist",
 BULLETPOINT = "bulletpoint",
 DIVIDER = "divider",
 TABLE = "table",
 EMBED = "embed",
}
